apiVersion: apps/v1
kind: Deployment
metadata:
  name: vanillamc
spec:
  replicas: 1 #only one mc server
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: minecraft
  template:
    metadata:
      labels:
        app: minecraft
    spec:
      containers:
      - name: minecraft
        image: itzg/minecraft-server
        resources:
          requests:
            memory: 4Gi
            cpu: 1
        env:
        - name: EULA
          value: "TRUE"
        - name: TYPE
          value: PAPER
        - name: VERSION
          value: "LATEST"
        - name: MEMORY
          value: 4G
        - name: MODS_FILE
          value: /data/mods.txt
        - name: SEED
          value: "Glacier"
        - name: VIEW_DISTANCE
          value: "16"
        - name: OPS
          value: adeeb7861
        ports:
        - name: server-port
          containerPort: 25565
          hostPort: 25565
        volumeMounts:
        - name: vanillamc
          mountPath: /data
      volumes:
      - name: vanillamc
        persistentVolumeClaim:
          claimName: vanillamc-pvc
