apiVersion: apps/v1
kind: Deployment
metadata:
  name: thehomiesmc
spec:
  replicas: 1 #only one mc server
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: minecraft
  template:
    metadata:
      labels:
        app: minecraft
    spec:
      containers:
      - name: minecraft
        image: itzg/minecraft-server
        resources:
          requests:
            memory: 8Gi
            cpu: 1
        env:
        - name: EULA
          value: TRUE
        - name: TYPE
          value: FORGE
        - name: VERSION
          value: 1.18.1
        - name: MEMORY
          value: 8G
        ports:
        - name: server-port
          containerPort: 25565
          hostPort: 25565
        volumeMounts:
        - name: thehomiesmc
          mountPath: /data
      volumes:
      - name: thehomiesmc
        persistentVolumeClaim:
          claimName: thehomies-pvc