# creating the persistent volume and claim for the server
apiVersion: v1
kind: PersistentVolume
metadata:
  name: thehomies-pv
spec:
  storageClassName: manual
  capacity:
    storage: 25Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/serverdata/thehomiesmc"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: thehomies-pvc
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 25Gi